<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VKEB79BA" failures="1" tests="7" name="topic_TestNGExamples.Test6_dependsOnMethods2" time="25.517" errors="0" timestamp="2023-12-02T20:27:37 IST" skipped="0">
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="type_UserName" time="5.315"/>
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="verifySDLogin" time="0.023">
    <failure message="expected [https://www.bhanusaucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.html]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.bhanusaucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.html]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at topic_TestNGExamples.Test6_dependsOnMethods2.verifySDLogin(Test6_dependsOnMethods2.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifySDLogin -->
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="setup" time="3.564"/>
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="click_Login" time="5.281"/>
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="type_Password" time="5.122"/>
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="gotoURL" time="6.041"/>
  <testcase classname="topic_TestNGExamples.Test6_dependsOnMethods2" name="teardown" time="0.171"/>
</testsuite> <!-- topic_TestNGExamples.Test6_dependsOnMethods2 -->
